### ISSUE TITLE
Investigate failed denoising subjects

### ISSUE THREAD

**Issue by tsalo** [NBCLab/power-replication#15]
- Dataset dset-camcan subject sub-CC110187 missing MEDN file.
- Dataset dset-camcan subject sub-CC110411 missing MEDN file.
- Dataset dset-camcan subject sub-CC310142 missing MEDN file.
- Dataset dset-camcan subject sub-CC420587 missing MEDN file.
- Dataset dset-camcan subject sub-CC620026 missing MEDN file.
- Dataset dset-dupre subject sub-16 missing:
    - sub-16_task-rest_run-1_desc-RVReg_bold.nii.gz
    - sub-16_task-rest_run-1_desc-RVTReg_bold.nii.gz

**Comment by tsalo** [comment]
The CamCAN failures seem to be due to failed SVDs during the tedana workflow.

**Comment by tsalo** [comment]
sub-16 failed due to missing physio regressors. Traceback when running the peakdet step:

```python
Traceback (most recent call last):
  File "05a_generate_physio_confounds.py", line 737, in <module>
    _main()
  File "05a_generate_physio_confounds.py", line 732, in _main
    main(project_dir=project_dir)
  File "05a_generate_physio_confounds.py", line 690, in main
    subject,
  File "05a_generate_physio_confounds.py", line 221, in compile_physio_regressors
    assert resp_data.shape[0] >= resp_data_end
AssertionError
```

**Comment by tsalo** [comment]
sub-16 doesn't have complete physio data, which explains why it was failing.
